In [0]:
import pandas as pd
df=pd.read_csv("/Workspace/Users/priyanshbobade@gmail.com/Spotify Analytics/track_data_final.csv")

In [0]:
df.shape

(8778, 15)

In [0]:
df.columns.tolist()

['track_id',
 'track_name',
 'track_number',
 'track_popularity',
 'track_duration_ms',
 'explicit',
 'artist_name',
 'artist_popularity',
 'artist_followers',
 'artist_genres',
 'album_id',
 'album_name',
 'album_release_date',
 'album_total_tracks',
 'album_type']

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8778 entries, 0 to 8777
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8778 non-null   object
 1   track_name          8776 non-null   object
 2   track_number        8778 non-null   int64
 3   track_popularity    8778 non-null   int64
 4   track_duration_ms   8778 non-null   int64
 5   explicit            8778 non-null   bool
 6   artist_name         8774 non-null   object
 7   artist_popularity   8774 non-null   float64
 8   artist_followers    8774 non-null   float64
 9   artist_genres       8774 non-null   object
 10  album_id            8778 non-null   object
 11  album_name          8776 non-null   object
 12  album_release_date  8778 non-null   object
 13  album_total_tracks  8778 non-null   int64
 14  album_type          8778 non-null   object
dtypes: bool(1), float64(2), int64(4), object(8)
memory usage: 968.8+ KB

In [0]:
df.head()

                 track_id  ...   album_type
0  6pymOcrCnMuCWdgGVTvUgP  ...  compilation
1  2lWc1iJlz2NVcStV5fbtPG  ...       single
2  1msEuwSBneBKpVCZQcFTsU  ...        album
3  7bcy34fBT2ap1L4bfPsl9q  ...        album
4  0GLfodYacy3BJE7AI3A8en  ...        album

[5 rows x 15 columns]

In [0]:
df.sample(5,random_state=42)

                    track_id  ... album_type
2865  7zx1i0jGcFwMBurajgKlO7  ...     single
2603  11KHnqxnmOx8W5PyplVGrO  ...      album
8177  59OLI17MahTupGhjyxaslJ  ...      album
3146  7AFASza1mXqntmGtbxXprO  ...      album
4333  1UPDfqsVIZLEiZeMuUsni2  ...      album

[5 rows x 15 columns]

In [0]:
df.isnull().sum().sort_values(ascending=False)

artist_name           4
artist_popularity     4
artist_followers      4
artist_genres         4
track_name            2
album_name            2
track_id              0
track_number          0
track_popularity      0
track_duration_ms     0
explicit              0
album_id              0
album_release_date    0
album_total_tracks    0
album_type            0
dtype: int64

In [0]:
df.duplicated().sum()

np.int64(0)

In [0]:
df.describe()
df.describe(include="object")

                      track_id track_name  ... album_release_date album_type
count                     8778       8776  ...               8778       8778
unique                    8778       7465  ...               2390          3
top     6pymOcrCnMuCWdgGVTvUgP    Flowers  ...         2010-01-01      album
freq                         1          8  ...                 78       6022

[4 rows x 8 columns]

In [0]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()}")

track_id: 8778
track_name: 7465
track_number: 54
track_popularity: 99
track_duration_ms: 7248
explicit: 2
artist_name: 2548
artist_popularity: 96
artist_followers: 3765
artist_genres: 652
album_id: 5317
album_name: 4873
album_release_date: 2390
album_total_tracks: 82
album_type: 3

In [0]:
df.dtypes

track_id               object
track_name             object
track_number            int64
track_popularity        int64
track_duration_ms       int64
explicit                 bool
artist_name            object
artist_popularity     float64
artist_followers      float64
artist_genres          object
album_id               object
album_name             object
album_release_date     object
album_total_tracks      int64
album_type             object
dtype: object

In [0]:
df[df.isnull().any(axis=1)]


##This shows the rows having one minimum NULL value. These rows constitue 6 (0.068%) of our 8778 rows
##Hence these rows can be dropped without significant loss of data.

                    track_id  ... album_type
436   3QhfFRPkhPCR1RMJWV1gde  ...      album
1396  2NbsBSshscKIPRG3kwBbfo  ...     single
3618  37ns6v0HK4zMV1PpRLIsbx  ...     single
3885  5EhZC8GFOVXrpiUW22jncE  ...     single
3886  0fM9dEhUFV4MHDuJgrcfOv  ...      album
4170  6N21iOdTYgYjDK1AyS0iUW  ...     single

[6 rows x 15 columns]

In [0]:
df_clean=df.dropna().copy()

df_clean.shape

(8772, 15)

In [0]:
df_clean.isnull().sum()

track_id              0
track_name            0
track_number          0
track_popularity      0
track_duration_ms     0
explicit              0
artist_name           0
artist_popularity     0
artist_followers      0
artist_genres         0
album_id              0
album_name            0
album_release_date    0
album_total_tracks    0
album_type            0
dtype: int64

In [0]:
%sql
CREATE DATABASE IF NOT EXISTS spotify_bronze;

CREATE DATABASE IF NOT EXISTS spotify_silver;

CREATE DATABASE IF NOT EXISTS spotify_gold;

In [0]:
%sql
show databases

databaseName
default
if
information_schema
spotify_bronze
spotify_gold
spotify_silver